[cc-sdd]
fetch.url = "https://registry.npmjs.org/cc-sdd/-/cc-sdd-$ver.tgz"
src.manual = "2.1.1"

[ccusage]
fetch.url = "https://registry.npmjs.org/ccusage/-/ccusage-$ver.tgz"
src.manual = "18.0.5"

[claude-code]
fetch.url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-$ver.tgz"
src.manual = "2.1.62"

[disable-checkout-persist-credentials]
fetch.github = "suzuki-shunsuke/disable-checkout-persist-credentials"
src.manual = "v1.0.0"

[duckgo]
fetch.github = "sheepla/duckgo"
src.manual = "v0.1.1"

[firge]
fetch.url = "https://github.com/yuru7/Firge/releases/download/$ver/Firge_$ver.zip"
src.manual = "v0.3.0"

[firge-nerd]
fetch.url = "https://github.com/yuru7/Firge/releases/download/$ver/FirgeNerd_$ver.zip"
src.manual = "v0.3.0"

[gh-dep]
fetch.github = "jackchuka/gh-dep"
src.manual = "v0.10.1"

[gh-grep]
fetch.github = "k1LoW/gh-grep"
src.manual = "v1.2.5"

[gh-triage]
fetch.github = "k1LoW/gh-triage"
src.manual = "v0.11.0"

[ghalint]
fetch.github = "suzuki-shunsuke/ghalint"
src.manual = "v1.5.4"

[ghatm]
fetch.github = "suzuki-shunsuke/ghatm"
src.manual = "v1.0.0"

[ghq]
fetch.github = "x-motemen/ghq"
src.manual = "v1.8.1"

[git-wt]
fetch.github = "k1LoW/git-wt"
src.manual = "v0.25.0"

[gitlab-ci-ls]
fetch.github = "alesbrelih/gitlab-ci-ls"
src.manual = "1.2.4"

[gitlab-ci-verify]
fetch.github = "timo-reymann/gitlab-ci-verify"
src.manual = "v2.8.0"

[ibm-plex-sans-jp]
fetch.url = "https://github.com/IBM/plex/releases/download/$ver/ibm-plex-sans-jp.zip"
src.manual = "@ibm/plex-sans-jp@3.0.0"

[lazygit]
fetch.github = "jesseduffield/lazygit"
src.manual = "v0.59.0"

[octocov]
fetch.github = "k1LoW/octocov"
src.manual = "v0.74.4"

[pinact]
fetch.github = "suzuki-shunsuke/pinact"
src.manual = "v3.9.0"

[roots]
fetch.github = "k1LoW/roots"
src.manual = "v0.4.1"

[slack-reminder]
fetch.github = "skanehira/slack-reminder"
src.manual = "v0.1.1"

[sort-package-json]
fetch.github = "keithamus/sort-package-json"
src.manual = "v3.6.1"

[vim-startuptime]
fetch.github = "rhysd/vim-startuptime"
src.manual = "v1.3.2"
